### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran-alias#6]
Following more inclusive code style guidelines.

Probably should find some simple guide to reference, e.g.:
https://source.android.com/setup/contribute/respectful-code

**Comment by s-weigand** [comment]
`main` is the new default name for the `default branch` on github, so lets go with this, after #5 is merged.
As a reference https://github.com/github/renaming

**Comment by s-weigand** [comment]
Done, guess you should also change the default branch on [your fork](https://github.com/jsnel/pyglotaran-alias).
